---
author: Jo Charbonneau
title: Project Dataset and Topics
output: html
---

[Link to dataset](https://www.icpsr.umich.edu/web/NACJD/studies/38872)

Things you plan to investigate using this dataset:

- The frequency of police stops by age (possibly analyzing alongside race if possible?)
- Most common amount of officer present at police stop
- How many of those stopped at the time of the survey taken had encountered police within the last 12 months

Stat 351 topics you plan to cover during the analysis:

1. Web scraping
2. "Big" Data
3. Animated/Interactive graphics
4. APIs (if not necessarily appropriate, most likely PDF tools)

---

Comments:

- This dataset can just be outright downloaded, so I'm not sure it's going to allow you to demonstrate API use successfully

- I think you're going to have a major observation bias in this dataset (e.g. stops which are reported have more officers) -- that's not necessarily a problem, just something you should probably note at some point. 

- Where would you use PDF tools?

- I wouldn't call 100k records "big" - it easily fits into memory. Beyond that we won't get to the "big data" part of class until after this is due. 


You could actually scrape LPD reports that are public information and posted online. That might be interesting and local? :)
